# Generated by Django 3.1.7 on 2021-04-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_auto_20210405_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='trains',
            name='train_id',
        ),
        migrations.AddField(
            model_name='trains',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
