# Generated by Django 3.1.7 on 2021-04-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_auto_20210405_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trains',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
