# Generated by Django 3.1.7 on 2021-04-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_auto_20210405_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Trains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trains.trains'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trains.users'),
        ),
    ]
