# Generated by Django 3.1.7 on 2021-04-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0006_auto_20210405_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='types',
            field=models.CharField(choices=[('Normal', 'Express'), ('Express', 'Express')], max_length=20),
        ),
    ]
