# Generated by Django 3.1.7 on 2021-04-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0007_auto_20210405_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='train_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='uid',
        ),
    ]
