# Generated by Django 3.1.7 on 2021-04-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0010_auto_20210407_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='uid',
        ),
    ]
